// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package request

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonA5775eDecodeGithubComSoulgardenKickexBotRequest(in *jlexer.Lexer, out *GetPairsAndSubscribe) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = string(in.String())
		case "type":
			out.Type = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonA5775eEncodeGithubComSoulgardenKickexBotRequest(out *jwriter.Writer, in GetPairsAndSubscribe) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix)
		out.String(string(in.Type))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v GetPairsAndSubscribe) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonA5775eEncodeGithubComSoulgardenKickexBotRequest(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GetPairsAndSubscribe) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonA5775eEncodeGithubComSoulgardenKickexBotRequest(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GetPairsAndSubscribe) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonA5775eDecodeGithubComSoulgardenKickexBotRequest(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GetPairsAndSubscribe) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonA5775eDecodeGithubComSoulgardenKickexBotRequest(l, v)
}
