issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen
    - path: /
      linters:
        - gci
        - gofumpt
        - exhaustivestruct
        - wrapcheck
        - tagliatelle
  enable-all: true
