version: '3'

services:
  #  arbitrage:
  #    image: soulgarden/kickex-bot:1.0.51
  #    environment:
  #      CFG_PATH: /conf.local.json
  #    stop_signal: SIGINT
  #    volumes:
  #      - ./conf/conf.remote.json:/conf.local.json
  #      - ./storage:/storage
  #    command: [ "/bin/bot", "arbitrage" ]

  spread:
    image: soulgarden/kickex-bot:1.0.51
    environment:
      CFG_PATH: /conf.local.json
    stop_signal: SIGINT
    volumes:
      - ./conf/conf.remote.json:/conf.local.json
      - ./storage:/storage

#  buy:
#    image: soulgarden/kickex-bot:1.0.51
#    environment:
#      CFG_PATH: /conf.local.json
#    stop_signal: SIGINT
#    volumes:
#      - ./conf/conf.remote.json:/conf.local.json
#      - ./storage:/storage
#    command: [ "/bin/bot", "buy" ]
