version: '3'

services:
#  disbalance:
  #    container_name: disbalance
  #    image: soulgarden/kickex-bot:1.0.30
  #    environment:
  #      CFG_PATH: /conf.local.json
  #    stop_signal: SIGINT
  #    volumes:
  #      - ./conf/conf.remote.json:/conf.local.json
  #      - ./storage:/storage
  #    command: [ "/bin/bot", "disbalance" ]

  spread:
    container_name: spread
    image: soulgarden/kickex-bot:1.0.30
    environment:
      CFG_PATH: /conf.local.json
    stop_signal: SIGINT
    volumes:
      - ./conf/conf.remote.json:/conf.local.json
      - ./storage:/storage