version: '3'

services:
  disbalance:
    image: soulgarden/kickex-bot:1.0.44
    environment:
      CFG_PATH: /conf.local.json
    stop_signal: SIGINT
    volumes:
      - ./conf/conf.remote.json:/conf.local.json
      - ./storage:/storage
    command: [ "/bin/bot", "disbalance" ]

  spread:
    image: soulgarden/kickex-bot:1.0.44
    environment:
      CFG_PATH: /conf.local.json
    stop_signal: SIGINT
    volumes:
      - ./conf/conf.remote.json:/conf.local.json
      - ./storage:/storage

  spread_kishu:
    image: soulgarden/kickex-bot:1.0.44
    environment:
      CFG_PATH: /conf.local.json
    stop_signal: SIGINT
    volumes:
      - ./conf/kishu.conf.remote.json:/conf.local.json
      - ./storage:/storage
