// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package response

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonBed2650eDecodeGithubComSoulgardenKickexBotResponse(in *jlexer.Lexer, out *Balances) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = string(in.String())
		case "balance":
			if in.IsNull() {
				in.Skip()
				out.Balance = nil
			} else {
				in.Delim('[')
				if out.Balance == nil {
					if !in.IsDelim(']') {
						out.Balance = make([]*Balance, 0, 8)
					} else {
						out.Balance = []*Balance{}
					}
				} else {
					out.Balance = (out.Balance)[:0]
				}
				for !in.IsDelim(']') {
					var v1 *Balance
					if in.IsNull() {
						in.Skip()
						v1 = nil
					} else {
						if v1 == nil {
							v1 = new(Balance)
						}
						(*v1).UnmarshalEasyJSON(in)
					}
					out.Balance = append(out.Balance, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonBed2650eEncodeGithubComSoulgardenKickexBotResponse(out *jwriter.Writer, in Balances) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"balance\":"
		out.RawString(prefix)
		if in.Balance == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Balance {
				if v2 > 0 {
					out.RawByte(',')
				}
				if v3 == nil {
					out.RawString("null")
				} else {
					(*v3).MarshalEasyJSON(out)
				}
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Balances) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonBed2650eEncodeGithubComSoulgardenKickexBotResponse(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Balances) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonBed2650eEncodeGithubComSoulgardenKickexBotResponse(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Balances) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonBed2650eDecodeGithubComSoulgardenKickexBotResponse(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Balances) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonBed2650eDecodeGithubComSoulgardenKickexBotResponse(l, v)
}
func easyjsonBed2650eDecodeGithubComSoulgardenKickexBotResponse1(in *jlexer.Lexer, out *Balance) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "currencyCode":
			out.CurrencyCode = string(in.String())
		case "currencyName":
			out.CurrencyName = string(in.String())
		case "available":
			out.Available = string(in.String())
		case "reserved":
			out.Reserved = string(in.String())
		case "total":
			out.Total = string(in.String())
		case "account":
			out.Account = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonBed2650eEncodeGithubComSoulgardenKickexBotResponse1(out *jwriter.Writer, in Balance) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"currencyCode\":"
		out.RawString(prefix[1:])
		out.String(string(in.CurrencyCode))
	}
	{
		const prefix string = ",\"currencyName\":"
		out.RawString(prefix)
		out.String(string(in.CurrencyName))
	}
	{
		const prefix string = ",\"available\":"
		out.RawString(prefix)
		out.String(string(in.Available))
	}
	{
		const prefix string = ",\"reserved\":"
		out.RawString(prefix)
		out.String(string(in.Reserved))
	}
	{
		const prefix string = ",\"total\":"
		out.RawString(prefix)
		out.String(string(in.Total))
	}
	{
		const prefix string = ",\"account\":"
		out.RawString(prefix)
		out.Int(int(in.Account))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Balance) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonBed2650eEncodeGithubComSoulgardenKickexBotResponse1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Balance) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonBed2650eEncodeGithubComSoulgardenKickexBotResponse1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Balance) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonBed2650eDecodeGithubComSoulgardenKickexBotResponse1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Balance) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonBed2650eDecodeGithubComSoulgardenKickexBotResponse1(l, v)
}
