apiVersion: v1
kind: Service
metadata:
  name: {{ include "kickex-bot.fullname" . }}
  labels:
    {{- include "kickex-bot.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  clusterIP: None
  selector:
    {{- include "kickex-bot.selectorLabels" . | nindent 4 }}
