apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "kickex-bot.fullname" . }}
  labels:
    {{- include "kickex-bot.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "kickex-bot.fullname" . }}
  replicas: {{ int .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kickex-bot.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kickex-bot.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "kickex-bot.serviceAccountName" . }}
      securityContext:
       {{- toYaml .Values.securityContext | nindent 12 }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
{{/*          command: [ "sleep", "inf"]*/}}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - { name: storage, mountPath: /storage }
            - { name: config, subPath: config.json, mountPath: /conf/conf.local.json, readOnly: true }
      volumes:
        - { name: config, configMap: { name: {{ include "kickex-bot.fullname" . }}-config } }
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
        storageClassName: do-block-storage
